### ISSUE TITLE
onSelectChange error

### ISSUE THREAD

**Issue by fafino** [h920526/jQueryMultipleSelectBox#2]
Hi,
  I configure multipleSelectBox in this mode:

$("#email").multipleSelectBox({
        isTouchDeviceMode: true,
        onSelectChange: enableDelete,
    });

after selected and deselected find error: in the function isJQueryCollectionEquals($jq1, $jq2) $jq1.not is not a function

Bye

Fabio

**Comment by h920526** [comment]
0.8.2
